### ISSUE TITLE
Reorder elements can induce enormous tries

### ISSUE THREAD

**Issue by Richard57** [keymanapp/ldml-keyboards-dev#4]
If I understand correctly, the class Trie will generate a Node for each string matching the concatenation of a 'before' and a 'from' attribute of a reorder element.  However  the number of such strings can be enormous.  For example, for the seriously proposed reorder element 
```
<reorder from="\u1A60[\u1A20-\u1A49]" order="75"
             before="[\u1A69\u1A6A\u1A6C][\u1A55-\u1A5E\u1A62\u1A65-\u1A68\u1A6D-\u1A7F][\u1A55-\u1A5E\u1A62\u1A65-\u1A68\u1A6D-\u1A7F][\u1A55-\u1A5E\u1A62\u1A65-\u1A68\u1A6D-\u1A7F][\u1A55-\u1A5E\u1A62\u1A65-\u1A68\u1A6D-\u1A7F]"/>
```
there are about 150 million matching strings.  This overwhelms a 32-bit implementation.  For example, a keyboard definition containing this element failed with 'MemoryError' after one hour of wall time.  This was observed with both Python  2.7.12 and Python 3.5.2 on 32-bit Ununtu Xenial  uname -a:
`Linux JRWUBU2 4.4.0-163-generic #191-Ubuntu SMP Wed Sep 11 17:09:46 UTC 2019 i686 athlon i686 GNU/Linux
`

**Comment by mhosken** [comment]
While the proposal document that lead to this monster context was loose in its description here, I would probably take a very different route in actual implementation. For example, there is no way that someone is going to reasonably have 4 x \u1A55 typed after a vowel. So the huge multiplication can be reduced with care. But I would also recommend resolving some tricky reorderings at the point they are typed. E.g. \u1A63\u1A74\u1A75.

Ultimately the question is whether the specification has to be expanded to support regular expressions rather than class sequences.

Also, there is no requirement for a reference implementation to support everything perfectly. What it does need to show is agreed behaviour for the core specification. If it requires a 64-bit system and a lot of swap to handle some odd case, then so be it ;)

**Comment by mhosken** [comment]
No intent to fix for this code base
